[profile.default]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/','forge-std/=lib/forge-std/src/','lib/foundry-devops/src =foundry-devops/src']
src = "src"
out = "out"
libs = ["lib"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
